### ISSUE TITLE
local information

### ISSUE THREAD

**Issue by jdunfield** [plum-umd/tfp2016#1]
"Accomodation" → Accommodation
"Red line", etc. → Red Line

The term "beltway" is used but not defined (and should probably be capitalized).

"D.C." is occasionally used instead of DC.

"decent train service": What counts as "decent" is extremely subjective (e.g., the NEC is still slow compared to intercity trains in Europe).  "Frequent train service" would be less tendentious (NEC service is actually more frequent than on some of the major routes in Europe).

The page sometimes uses "metro", sometimes "public subway".  Do people in DC actually call Metrorail "the subway"?  If not, maybe it makes sense to use "metro" consistently.

When I visited UMD it was a definite win to buy a weekly Metrorail pass to commute in from downtown, but that was a couple years ago, so I don't know if that's still the case.

**Comment by dvanhorn** [comment]
Thanks!
